.dependent_changes: &dependent_changes
    changes:
      - .gitlab-ci.yml
      - "FuelingExampleApp/**/*"
      - "PACECloudSDK/**/*"

.only_merge_requests: &only_merge_requests
  only:
    refs:
      - merge_requests
    <<: *dependent_changes

.only_master: &only_master
  only:
    refs:
      - master
    <<: *dependent_changes

fuelingexampleapp_plists:
  extends: .plist
  variables:
    PROJECT_PATH: "FuelingExampleApp/FuelingExampleApp"
  only:
    <<: *dependent_changes

## Tests
fuelingexampleapp_code_style:
  extends: .code_style
  only:
   <<: *dependent_changes

## Build
.fuelingexampleapp_development_template:
  extends: .xcode_version
  <<: *only_master
  except:
    - schedules
  variables:
    PROJECT_PATH: "FuelingExampleApp"
  interruptible: true

fuelingexampleapp_build_development:
  extends: .fuelingexampleapp_development_template
  stage: build
  script:
    - cd $PROJECT_PATH
    - bundle exec fastlane build_development --env development
  artifacts:
    name: "latest-app"
    paths:
      - $PROJECT_PATH/artifacts/FuelingExampleApp.ipa
    expire_in: 2 days

## Review
.fuelingexampleapp_review_template:
  extends: .xcode_version
  <<: *only_merge_requests
  except:
    refs:
      - tags
    variables:
     - $CI_COMMIT_MESSAGE =~ /WIP/
  variables:
    PROJECT_PATH: "FuelingExampleApp"
  interruptible: true

fuelingexampleapp_build_review:
  extends: .fuelingexampleapp_review_template
  stage: build
  script:
    - cd $PROJECT_PATH
    - bundle exec fastlane build_development --env development
  artifacts:
    name: "review-app"
    paths:
      - $PROJECT_PATH/artifacts/FuelingExampleApp.ipa
    expire_in: 2 days
