include:
  - local: "ExampleApp/.gitlab-ci.yml"
  - local: "FuelingExampleApp/.gitlab-ci.yml"

variables:
  PROJECT_PATH: "PACECloudSDK"
  PROJECT_NAME: "PACECloudSDK"
  SIMULATOR_SDK: "iphonesimulator"
  DEVICE_SDK: "iphoneos"
  REPO_PLATFORM: "ios"
  REPO_BASE_URL: "https://repo.dev.k8s.pacelink.net/api"
  REPO_PROJECT_ID: ""

stages:
  - test
  - build
  - publish

before_script:
  - bundle install || true
  - export TAG_COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
  - echo "Commit time to be used as build number:" $TAG_COMMIT_TIME
  - export BUILD_NUMBER=$(TZ=Etc/Utc date -j -f '%s' ${TAG_COMMIT_TIME} "+%Y%m%d%H")
  - export VERSION_NAME=$(TZ=Etc/Utc date -j -f '%s' ${TAG_COMMIT_TIME} "+%y.%V.%u")
  - echo "Building version $VERSION_NAME with build number $BUILD_NUMBER"
  - export TAG_NAME=${CI_COMMIT_TAG:-'2.0.0'}
  - echo "Current tag version $TAG_NAME"

## Infrastructure
.xcode_version:
  tags:
    - m1-xcode-14.1

### PLists
.plist:
  extends: .xcode_version
  stage: test
  before_script:
    - echo "Ignore global before_script"
  after_script:
    - echo "Ignore global after_script"
  script:
    - cd $PROJECT_PATH
    - find . -name "*.strings" -size +0 -print0 | xargs -0 plutil -lint
  only:
    refs:
      - merge_requests
  interruptible: true

### Unit tests
.unit_test:
  extends: .xcode_version
  stage: test
  script:
    - cd $PROJECT_PATH
    - bundle exec fastlane test
  allow_failure: false
  only:
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /WIP/
  interruptible: true

### Code style
.code_style:
  extends: .xcode_version
  stage: test
  before_script:
    - echo "Ignore global before_script"
  after_script:
    - echo "Ignore global after_script"
  script:
    - swiftlint
  only:
    refs:
      - merge_requests
  interruptible: true

### Build
.review:
  extends: .xcode_version
  stage: build
  script:
    - xcodebuild -scheme $TARGET_SCHEME -sdk $SIMULATOR_SDK | xcpretty
  only:
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /WIP/
  interruptible: true

.xcframework: &xcframework
  script:
    - bundle exec fastlane set_version version_number:$TAG_NAME
    - xcodebuild archive
      -scheme $PROJECT_NAME
      -sdk $DEVICE_SDK
      -archivePath "archives/ios_devices.xcarchive" BUILD_LIBRARY_FOR_DISTRIBUTION=YES SKIP_INSTALL=NO | xcpretty
    - xcodebuild archive
      -scheme $PROJECT_NAME
      -sdk $SIMULATOR_SDK
      -archivePath "archives/ios_simulators.xcarchive" BUILD_LIBRARY_FOR_DISTRIBUTION=YES SKIP_INSTALL=NO | xcpretty
    - xcodebuild
      -create-xcframework
      -framework archives/ios_devices.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework
      -framework archives/ios_simulators.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework
      -output build/${PROJECT_NAME}.xcframework | xcpretty
  interruptible: true

### Commit format
commit_format:
  stage: test
  before_script:
    - echo "Ignore global before_script"
  after_script:
    - echo "Ignore global after_script"
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${GIT_BASE_URL}/pace/mobile/common.git tmp/common
    - python3 tmp/common/scripts/validate_commit.py --project-id $CI_PROJECT_ID --merge-request-iid $CI_MERGE_REQUEST_IID
  only:
    - merge_requests
  tags:
    - xcode-12.4
  interruptible: true

pacecloudsdk_plists:
 extends: .plist

pacecloudsdk_code_style:
  extends: .code_style

pacecloudsdk_unit_tests:
  extends: .unit_test
  variables:
    PROJECT_PATH: "."

## Build framework
framework_review:
  extends: .review
  stage: build
  variables:
    TARGET_SCHEME: "PACECloudSDK"

framework_slim_review:
  extends: .review
  stage: build
  variables:
    TARGET_SCHEME: "PACECloudSlimSDK"

framework_watch_review:
  extends: .review
  stage: build
  variables:
    SIMULATOR_SDK: "watchsimulator"
    TARGET_SCHEME: "PACECloudWatchSDK"

## Build xcframework
framework_release_build:
  extends: .xcode_version
  stage: build
  <<: *xcframework
  only:
    - tags
  artifacts:
    name: $PROJECT_NAME
    paths:
      - ./build/
    expire_in: 1 week
  interruptible: true

## Build slim xcframework
framework_slim_release_build:
  extends: .xcode_version
  variables:
    PROJECT_NAME: "PACECloudSlimSDK"
  stage: build
  <<: *xcframework
  only:
    refs:
      - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /WIP/
  artifacts:
    name: "PACECloudSlimSDK"
    paths:
      - ./build/
    expire_in: 1 week
  when: manual
  interruptible: true

## Build watch xcframework
framework_watch_release_build:
  extends: .xcode_version
  variables:
    PROJECT_NAME: "PACECloudWatchSDK"
    SIMULATOR_SDK: "watchsimulator"
    DEVICE_SDK: "watchos"
  stage: build
  <<: *xcframework
  only:
    refs:
      - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /WIP/
  artifacts:
    name: "PACECloudWatchSDK"
    paths:
      - ./build/
    expire_in: 1 week
  when: manual
  interruptible: true

# Update CocoaPods trunk
framework_publish_pods:
  extends: .xcode_version
  stage: publish
  script:
    - pod trunk push PACECloudSDK.podspec --allow-warnings
  only:
    - tags

# Documentation
documentation:
  extends: .xcode_version
  stage: build
  script:
    - xcodebuild docbuild -scheme $TARGET_SCHEME -sdk $SIMULATOR_SDK | xcpretty
    - find ~/Library/Developer/Xcode/DerivedData
      -name "$TARGET_SCHEME.doccarchive"
      -exec cp -R {} ./docs \;
  only:
    - tags
  allow_failure: true
  variables:
    TARGET_SCHEME: "PACECloudSDK"
  artifacts:
    paths:
      - ./docs/${TARGET_SCHEME}.doccarchive
    name: "ios-pace-cloud-sdk-$TAG_NAME"
    expire_in: 1 week

# GitHub Release
framework_publish_github:
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${COMMON_REPO} tmp/common
    - pip3 install -r tmp/common/scripts/tags/requirements.txt
    - python3 tmp/common/scripts/tags/create_github_release.py -d pace/cloud-sdk-ios
  tags:
    - xcode-12.4
  allow_failure: true
  stage: publish
  only:
    - tags
  when: manual
