clean: true
author: PACE Telematics GmbH
author_url: https://www.pace.car
copyright: PACE Telematics GmbH
readme: README.md
theme: apple
docset_path: docs
source_directory: '.'           
output: generated/docs
github_url: https://github.com/pace/cloud-sdk-ios
exclude: ExampleApp
sdk: [os|simulator]
