// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tile_query_request.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct TileQueryRequest: SwiftProtobuf.Message {
  static let protoMessageName: String = "TileQueryRequest"

  var zoom: UInt32 = 0

  var areas: [TileQueryRequest.AreaQuery] = []

  var tiles: [TileQueryRequest.IndividualTileQuery] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct AreaQuery: SwiftProtobuf.Message {
    static let protoMessageName: String = TileQueryRequest.protoMessageName + ".AreaQuery"

    var northEast: TileQueryRequest.Coordinate {
      get { return _storage._northEast ?? TileQueryRequest.Coordinate() }
      set { _uniqueStorage()._northEast = newValue }
    }
    /// Returns true if `northEast` has been explicitly set.
    var hasNorthEast: Bool { return _storage._northEast != nil }
    /// Clears the value of `northEast`. Subsequent reads from it will return its default value.
    mutating func clearNorthEast() { _storage._northEast = nil }

    var southWest: TileQueryRequest.Coordinate {
      get { return _storage._southWest ?? TileQueryRequest.Coordinate() }
      set { _uniqueStorage()._southWest = newValue }
    }
    /// Returns true if `southWest` has been explicitly set.
    var hasSouthWest: Bool { return _storage._southWest != nil }
    /// Clears the value of `southWest`. Subsequent reads from it will return its default value.
    mutating func clearSouthWest() { _storage._southWest = nil }

    var invalidationToken: UInt64 {
      get { return _storage._invalidationToken }
      set { _uniqueStorage()._invalidationToken = newValue }
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    /// Used by the decoding initializers in the SwiftProtobuf library, not generally
    /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
    /// initializers are defined in the SwiftProtobuf library. See the Message and
    /// Message+*Additions` files.
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
      _ = _uniqueStorage()
      try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
        while let fieldNumber = try decoder.nextFieldNumber() {
          switch fieldNumber {
          case 1: try decoder.decodeSingularMessageField(value: &_storage._northEast)
          case 2: try decoder.decodeSingularMessageField(value: &_storage._southWest)
          case 3: try decoder.decodeSingularUInt64Field(value: &_storage._invalidationToken)
          default: break
          }
        }
      }
    }

    /// Used by the encoding methods of the SwiftProtobuf library, not generally
    /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
    /// other serializer methods are defined in the SwiftProtobuf library. See the
    /// `Message` and `Message+*Additions` files.
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
      try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
        if let v = _storage._northEast {
          try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if let v = _storage._southWest {
          try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        }
        if _storage._invalidationToken != 0 {
          try visitor.visitSingularUInt64Field(value: _storage._invalidationToken, fieldNumber: 3)
        }
      }
      try unknownFields.traverse(visitor: &visitor)
    }

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  struct IndividualTileQuery: SwiftProtobuf.Message {
    static let protoMessageName: String = TileQueryRequest.protoMessageName + ".IndividualTileQuery"

    var geo: TileQueryRequest.Coordinate {
      get { return _storage._geo ?? TileQueryRequest.Coordinate() }
      set { _uniqueStorage()._geo = newValue }
    }
    /// Returns true if `geo` has been explicitly set.
    var hasGeo: Bool { return _storage._geo != nil }
    /// Clears the value of `geo`. Subsequent reads from it will return its default value.
    mutating func clearGeo() { _storage._geo = nil }

    var invalidationToken: UInt64 {
      get { return _storage._invalidationToken }
      set { _uniqueStorage()._invalidationToken = newValue }
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    /// Used by the decoding initializers in the SwiftProtobuf library, not generally
    /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
    /// initializers are defined in the SwiftProtobuf library. See the Message and
    /// Message+*Additions` files.
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
      _ = _uniqueStorage()
      try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
        while let fieldNumber = try decoder.nextFieldNumber() {
          switch fieldNumber {
          case 1: try decoder.decodeSingularMessageField(value: &_storage._geo)
          case 3: try decoder.decodeSingularUInt64Field(value: &_storage._invalidationToken)
          default: break
          }
        }
      }
    }

    /// Used by the encoding methods of the SwiftProtobuf library, not generally
    /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
    /// other serializer methods are defined in the SwiftProtobuf library. See the
    /// `Message` and `Message+*Additions` files.
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
      try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
        if let v = _storage._geo {
          try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if _storage._invalidationToken != 0 {
          try visitor.visitSingularUInt64Field(value: _storage._invalidationToken, fieldNumber: 3)
        }
      }
      try unknownFields.traverse(visitor: &visitor)
    }

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  struct Coordinate: SwiftProtobuf.Message {
    static let protoMessageName: String = TileQueryRequest.protoMessageName + ".Coordinate"

    var x: UInt32 = 0

    var y: UInt32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    /// Used by the decoding initializers in the SwiftProtobuf library, not generally
    /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
    /// initializers are defined in the SwiftProtobuf library. See the Message and
    /// Message+*Additions` files.
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularUInt32Field(value: &self.x)
        case 2: try decoder.decodeSingularUInt32Field(value: &self.y)
        default: break
        }
      }
    }

    /// Used by the encoding methods of the SwiftProtobuf library, not generally
    /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
    /// other serializer methods are defined in the SwiftProtobuf library. See the
    /// `Message` and `Message+*Additions` files.
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
      if self.x != 0 {
        try visitor.visitSingularUInt32Field(value: self.x, fieldNumber: 1)
      }
      if self.y != 0 {
        try visitor.visitSingularUInt32Field(value: self.y, fieldNumber: 2)
      }
      try unknownFields.traverse(visitor: &visitor)
    }
  }

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt32Field(value: &self.zoom)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.areas)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.tiles)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.zoom != 0 {
      try visitor.visitSingularUInt32Field(value: self.zoom, fieldNumber: 1)
    }
    if !self.areas.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.areas, fieldNumber: 2)
    }
    if !self.tiles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tiles, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension TileQueryRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "zoom"),
    2: .same(proto: "areas"),
    3: .same(proto: "tiles")
  ]

  func _protobuf_generated_isEqualTo(other: TileQueryRequest) -> Bool {
    if self.zoom != other.zoom { return false }
    if self.areas != other.areas { return false }
    if self.tiles != other.tiles { return false }
    if unknownFields != other.unknownFields { return false }
    return true
  }
}

extension TileQueryRequest.AreaQuery: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "north_east"),
    2: .standard(proto: "south_west"),
    3: .standard(proto: "invalidation_token")
  ]

  fileprivate class _StorageClass {
    var _northEast: TileQueryRequest.Coordinate?
    var _southWest: TileQueryRequest.Coordinate?
    var _invalidationToken: UInt64 = 0

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _northEast = source._northEast
      _southWest = source._southWest
      _invalidationToken = source._invalidationToken
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  func _protobuf_generated_isEqualTo(other: TileQueryRequest.AreaQuery) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._northEast != other_storage._northEast { return false }
        if _storage._southWest != other_storage._southWest { return false }
        if _storage._invalidationToken != other_storage._invalidationToken { return false }
        return true
      }
      if !storagesAreEqual { return false }
    }
    if unknownFields != other.unknownFields { return false }
    return true
  }
}

extension TileQueryRequest.IndividualTileQuery: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "geo"),
    3: .standard(proto: "invalidation_token")
  ]

  fileprivate class _StorageClass {
    var _geo: TileQueryRequest.Coordinate?
    var _invalidationToken: UInt64 = 0

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _geo = source._geo
      _invalidationToken = source._invalidationToken
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  func _protobuf_generated_isEqualTo(other: TileQueryRequest.IndividualTileQuery) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._geo != other_storage._geo { return false }
        if _storage._invalidationToken != other_storage._invalidationToken { return false }
        return true
      }
      if !storagesAreEqual { return false }
    }
    if unknownFields != other.unknownFields { return false }
    return true
  }
}

extension TileQueryRequest.Coordinate: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "x"),
    2: .same(proto: "y")
  ]

  func _protobuf_generated_isEqualTo(other: TileQueryRequest.Coordinate) -> Bool {
    if self.x != other.x { return false }
    if self.y != other.y { return false }
    if unknownFields != other.unknownFields { return false }
    return true
  }
}
