default_platform(:ios)

platform :ios do
  
  desc 'Run tests'
  lane :test do
    scan(
      project: 'PACECloudSDK.xcodeproj',
      scheme: 'PACECloudSDKTests',
      reset_simulator: true, 
      force_quit_simulator: true, 
      prelaunch_simulator: true, 
      reinstall_app: true,
      xcargs: "-skipPackagePluginValidation -skipMacroValidation"
    )
  end

  lane :set_version do |options|
    set_info_plist_value(path: 'PACECloudSDK/Info.plist', key: 'CFBundleShortVersionString', value: options[:version_number])
    set_info_plist_value(path: 'PACECloudSDK/Utils/Plists/FallbackVersions.plist', key: 'ReleaseVersion', value: options[:version_number])
  end

  lane :bump_podspec do |options|
    version_bump_podspec(path: "PACECloudSDK.podspec", version_number: "#{options[:version_number]}")
  end

  lane :create_github_release do |options|
    new_sdk_version = options[:new_sdk_version]

    # Somehow when working with File the current working directory is the fastlane directory
    # but when passing the assets to the 'set_github_release' lane the cwd is the root directory of the sdk
    assets = []

    if File.exist?("../build/PACECloudSDK.zip")
      assets.append("./build/PACECloudSDK.zip")
    end

    if File.exist?("../build/PACECloudSlimSDK.zip")
      assets.append("./build/PACECloudSlimSDK.zip")
    end

    if File.exist?("../build/PACECloudWatchSDK.zip")
      assets.append("./build/PACECloudWatchSDK.zip")
    end

    set_github_release(
      repository_name: "pace/cloud-sdk-ios",
      api_token: ENV["GITHUB_API_TOKEN"],
      name: new_sdk_version,
      tag_name: new_sdk_version,
      description: (File.read("../build/release_notes_#{new_sdk_version}.md") rescue "No changelog provided"),
      commitish: "master",
      upload_assets: assets
    )
  end
end