default_platform(:ios)

platform :ios do
  before_all do
    carthage(command: 'bootstrap', cache_builds: true,  platform: 'iOS', use_binaries: false)
  end
  
  lane :build_framework do |options|
    carthage(
      command: 'build',
      no_skip_current: true,
      cache_builds: true,
      platform: 'iOS'
    )

    if options[:archive]
        carthage(
          frameworks: ['PACECloudSDK'],
          output: 'PACECloudSDK.framework.zip',
          command: 'archive'
        )
    end
  end

  desc 'Run tests'
  lane :test do
    scan(
      project: 'PACECloudSDK.xcodeproj',
      scheme: 'PACECloudSDKTests',
      reset_simulator: true, 
      force_quit_simulator: true, 
      prelaunch_simulator: true, 
      reinstall_app: true
    )
  end
end
