default_platform(:ios)

platform :ios do
  
  desc 'Run tests'
  lane :test do
    scan(
      project: 'PACECloudSDK.xcodeproj',
      scheme: 'PACECloudSDKTests',
      reset_simulator: true, 
      force_quit_simulator: true, 
      prelaunch_simulator: true, 
      reinstall_app: true,
      xcargs: "-skipPackagePluginValidation -skipMacroValidation"
    )
  end

  lane :set_version do |options|
    set_info_plist_value(path: 'PACECloudSDK/Info.plist', key: 'CFBundleShortVersionString', value: options[:version_number])
    set_info_plist_value(path: 'PACECloudSDK/Utils/Plists/FallbackVersions.plist', key: 'ReleaseVersion', value: options[:version_number])
  end

  lane :bump_podspec do |options|
    version_bump_podspec(path: "PACECloudSDK.podspec", version_number: "#{options[:version_number]}")
  end

  lane :create_github_release do |options|
    new_sdk_version = options[:new_sdk_version]

    set_github_release(
      repository_name: "pace/cloud-sdk-ios",
      api_token: ENV["GITHUB_API_TOKEN"],
      name: new_sdk_version,
      tag_name: new_sdk_version,
      description: (File.read("../build/release_notes_#{new_sdk_version}.md") rescue "No changelog provided"),
      commitish: "master",
      upload_assets: ["./build/PACECloudSDK.zip", "./build/PACECloudSlimSDK.zip", "./build/PACECloudWatchSDK.zip"]
    )
  end
end