default_platform(:ios)

PROJECT_PATH = 'PACECloudSDKExample.xcodeproj'
TEAM_ID = ENV['TEAM_ID']
APP_IDENTIFIER = ENV['APP_IDENTIFIER']

platform :ios do
  minimum_ios_version = '11.0'
  version_number = ENV['VERSION_NAME']
  build_number = ENV['BUILD_NUMBER']
  
  before_all do
    clear_derived_data

    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
      verbose: true
    )
  end

  after_all do
    copy_artifacts(
      keep_original: false,
      target_path: 'artifacts',
      artifacts: ['*.cer', '*.mobileprovision', '*.ipa'],
      fail_on_missing: true
    )

    delete_keychain(name: ENV['MATCH_KEYCHAIN_NAME'])
  end

  desc 'Run tests'
  lane :test do
    scan(
      project: 'PACECloudSDK.xcodeproj',
      scheme: 'PACECloudSDKTests',
      reset_simulator: true, 
      force_quit_simulator: true, 
      prelaunch_simulator: true, 
      reinstall_app: true,
      xcargs: "-skipPackagePluginValidation -skipMacroValidation"
    )
  end

  desc 'Build development build'
  lane :build_development do
    build_example_app(config: 'Development')
  end

  desc 'Build example app'
  lane :build_example_app do |options|
    app_store_connect_api_key(in_house: false)

    case options[:config]
    when 'Development'
      add_badge(alpha: true)
    end

    info_plist_path = "PACECloudSDKExample/Info.plist"

    set_info_plist_value(path: info_plist_path, key: 'CFBundleShortVersionString', value: version_number)
    set_info_plist_value(path: info_plist_path, key: 'CFBundleVersion', value: build_number)

    update_code_signing_settings(
      use_automatic_signing: false,
      path: PROJECT_PATH,
      team_id: TEAM_ID
    )

    update_app_identifier(
      xcodeproj: PROJECT_PATH,
      plist_path: info_plist_path, # Path to info plist file, relative to xcodeproj
      app_identifier: APP_IDENTIFIER
    )

    match(
      type: 'development',
      team_id: TEAM_ID,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      app_identifier: APP_IDENTIFIER,
      verbose: true
    )

    update_project_provisioning(
      xcodeproj: PROJECT_PATH,
      target_filter: 'PACECloudSDKExample',
      profile: ENV["sigh_#{APP_IDENTIFIER}_development_profile-path"],
      build_configuration: options[:config]
    )

    update_project_team(
      path: PROJECT_PATH,
      targets: "PACECloudSDKExample",
      teamid: TEAM_ID
    )

    gym(
      clean: true,
      export_method: 'development',
      scheme: 'PACECloudSDKExample',
      export_team_id: TEAM_ID,
      configuration: options[:config],
      export_options: {
        method: 'development',
        compileBitcode: false,
        provisioningProfiles: {
          APP_IDENTIFIER => ENV["sigh_#{APP_IDENTIFIER}_development_profile-name"]
        }
      },
      codesigning_identity: 'Apple Development',
      xcargs: "-skipPackagePluginValidation -skipMacroValidation CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=#{TEAM_ID}"
    )
  end
end