.dependent_changes: &dependent_changes
    changes:
      - .gitlab-ci.yml
      - "ExampleApp/**/*"
      - "PACECloudSDK/**/*"

.only_merge_requests: &only_merge_requests
  only:
    refs:
      - merge_requests
    <<: *dependent_changes

.only_master: &only_master
  only:
    refs:
      - master
    <<: *dependent_changes

pacecloudsdkexample_plists:
  extends: .plist
  variables:
    PROJECT_PATH: "ExampleApp/PACECloudSDKExample"
  only:
    <<: *dependent_changes

## Tests
pacecloudsdkexample_code_style:
  extends: .code_style
  only:
   <<: *dependent_changes

## Build
.pacecloudsdkexample_development_template:
  extends: .xcode_version
  <<: *only_master
  except:
    - schedules
  environment:
    name: development
  variables:
    PROJECT_PATH: "ExampleApp"
  interruptible: true

pacecloudsdkexample_build_development:
  extends: .pacecloudsdkexample_development_template
  stage: build
  script:
    - cd $PROJECT_PATH
    - bundle exec fastlane build_development --env development
  artifacts:
    name: "latest-app"
    paths:
      - $PROJECT_PATH/artifacts/PACECloudSDKExample.ipa
    expire_in: 2 days

## Review
.pacecloudsdkexample_review_template:
  extends: .xcode_version
  <<: *only_merge_requests
  except:
    refs:
      - tags
    variables:
     - $CI_COMMIT_MESSAGE =~ /WIP/
  variables:
    PROJECT_PATH: "ExampleApp"
  interruptible: true

pacecloudsdkexample_build_review:
  extends: .pacecloudsdkexample_review_template
  stage: build
  script:
    - cd $PROJECT_PATH
    - bundle exec fastlane build_development --env development
  environment:
    name: review/$CI_COMMIT_REF_NAME
  artifacts:
    name: "review-app"
    paths:
      - $PROJECT_PATH/artifacts/PACECloudSDKExample.ipa
    expire_in: 2 days
